### PR TITLE
Support for transforming raw values

### LINKED ISSUE #2: Support for transforming scalar values
I have a use case where the source value is not provided as a JSON object or array, but as a number.
I'd like to transform the number using an $eval statement, e.g.:

* Context: `-12.34`
* Template: `$eval: '0 - ${.}'`
* Result: `12.34`

This is not possible with json-e because the context is required to be a JSON object (see https://github.com/taskcluster/json-e/issues/408). The proposed solution is wrapping the scalar value in a JSON object.

Maybe this could be implemented by an additional configuration option ("wrap to `{ "value": "$value" }` if not an object") or another kind of transform. Another approach is support for a general purpose javascript transformer, but this is not required for my use case.

I'm requesting this feature because this project perfectly fits the needs for my use case in all other aspects.

### PR DESCRIPTION
**Pull request by git-developer**
Closes #2.

### CODE REVIEW

**Comment by tg44** [comment]
Seems ok, but; shouldn't we add this to the `filterIfHasData` method too?

**Comment by tg44** [comment]
Also if your use-case can be interesting to others, can you add that to the recipes?

**Comment by git-developer** [comment]
Yes, both are good ideas, I will extend the pull request accordingly.

**Comment by git-developer** [comment]
All changes are applied. Is it possible to preview the rendered recipe?

**Comment by git-developer** [comment]
I configured GitHub Pages for my development branch so that a [recipe preview](https://git-developer.github.io/mqtt-transformer/recipes/power-consumed-to-power-provided.html) is available.

**Comment by tg44** [comment]
Thanks for your contribution!

**Pull request merged**
